spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:file:./target/h2db/db/databaseDev;DB_CLOSE_DELAY=-1
    username: root
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/dbchangelog-dev.xml

server:
  port: 8080
